---
# tasks file for roles/manage_interfaces

- ansible.builtin.debug:
    msg:
      - "----------------------------------------------------------------"
      - "+             Calling Role - [manage_interfaces]               +"
      - "----------------------------------------------------------------"
  tags:
    - mi_vpc
    - mi_hosts
    - mi_loopback
    - mi_all

- name: Include Tasks To Manage vPC Interfaces
  ansible.builtin.import_tasks: vpc_interfaces.yml
  tags:
    - mi_vpc
    - mi_all

- name: Include Tasks To Manage Loopback Interfaces
  ansible.builtin.import_tasks: loopback_interfaces.yml
  tags:
    - mi_loopback
    - mi_all


- name: Include Tasks To Manage Host Facing Interfaces
  ansible.builtin.import_tasks: host_interfaces.yml
  tags:
    - mi_hosts
    - mi_all

