---
- name: Intialize create_fabric_ext Flag
  ansible.builtin.set_fact:
    create_fabric_ext: true

- name: "Check If Fabric Exists - {{ fabric_external.name }}"
  ansible.builtin.set_fact:
    create_fabric_ext: false
  when: item.fabricName == fabric_external.name
  loop: "{{ create_fabric_result.response.DATA }}"
  loop_control:
    label: "{{ item.fabricName }}"

- name: Check If Fabric Exists Log
  ansible.builtin.debug:
    msg: "Fabric {{ fabric_external.name }} Already Exists"
  when: not create_fabric_ext

- name: Create External Fabric on NDFC
  vars:
    create_fabric_payload:
      BGP_AS: "{{ fabric_external.asn }}"
      IS_READ_ONLY: false
  cisco.dcnm.dcnm_rest:
    method: POST
    path: "/appcenter/cisco/ndfc/api/v1/lan-fabric/rest/control/fabrics/{{ fabric_external.name }}/External_Fabric"
    json_data: "{{ create_fabric_payload | to_json }}"
  when: create_fabric_ext
