---

- name: Intialize create_fabric_flag
  ansible.builtin.set_fact:
    create_fabric_flag: true

- name: Check If Fabric Exists
  ansible.builtin.set_fact:
    create_fabric_flag: false
  when: item.fabricName == fabric.name
  loop: "{{ create_fabric_result.response.DATA }}"
  loop_control:
    label: "{{ item.fabricName }}"

- name: Check If Fabric Exists Log
  ansible.builtin.debug:
    msg: "Fabric {{ fabric.name }} Already Exists"
  when: not create_fabric_flag

- name: Create Fabric on NDFC - {{ fabric.name }}
  vars:
    create_fabric_payload: "{{ fabric_settings.vrf_lite }}"
  cisco.dcnm.dcnm_rest:
    method: POST
    path: "/appcenter/cisco/ndfc/api/v1/lan-fabric/rest/control/fabrics/{{ fabric.name }}/Easy_Fabric"
    json_data: "{{ create_fabric_payload | to_json }}"
  when: create_fabric_flag

- name: Update Fabric Settings on NDFC - {{ fabric.name }}
  vars:
    create_fabric_payload: "{{ fabric_settings.poap }}"
  cisco.dcnm.dcnm_rest:
    method: PUT
    path: "/appcenter/cisco/ndfc/api/v1/lan-fabric/rest/control/fabrics/{{ fabric.name }}/Easy_Fabric"
    json_data: "{{ create_fabric_payload | to_json }}"
  when: fabric_poap.enable_poap and create_fabric_flag
