---
# tasks file for roles/create_fabric

- name: Role Entry Point - [create_fabric]
  ansible.builtin.debug:
    msg:
      - "----------------------------------------------------------------"
      - "+             Calling Role - [create_fabric]                   +"
      - "----------------------------------------------------------------"
  tags:
    - cf_vxlan
    - cf_external
    - cf_poap
    - cf_all

- name: Include Tasks To Create Fabric
  ansible.builtin.import_tasks: manage_fabric.yml
  tags:
    - cf_vxlan
    - cf_all

- name: Include Tasks To Create External Fabric
  ansible.builtin.import_tasks: manage_external_fabric.yml
  tags:
    - cf_external
    - cf_all
