---

- name: Query NDFC for Fabric
  cisco.dcnm.dcnm_rest:
    method: GET
    path: "/appcenter/cisco/ndfc/api/v1/lan-fabric/rest/control/fabrics"
  register: create_fabric_result

- name: Intialize create_fabric_ext Flag
  ansible.builtin.set_fact:
    create_fabric_ext: true

- name: Check If Fabric Exists in NDFC
  ansible.builtin.set_fact:
    create_fabric_ext: false
  when: item.fabricName == fabric_external_settings.FABRIC_NAME
  loop: "{{ create_fabric_result.response.DATA }}"
  loop_control:
    label: "{{ item.fabricName }}"

- name: Check If Fabric Exists in NDFC Log
  ansible.builtin.debug:
    msg: "Fabric {{ fabric_external_settings.FABRIC_NAME }} Already Exists"
  when: not create_fabric_ext

- name: Create External Fabric {{ fabric_external_settings.FABRIC_NAME }} in NDFC
  vars:
    create_fabric_payload:
      BGP_AS: "{{ fabric_external_settings.BGP_AS }}"
      IS_READ_ONLY: false
  cisco.dcnm.dcnm_rest:
    method: POST
    path: "/appcenter/cisco/ndfc/api/v1/lan-fabric/rest/control/fabrics/{{ fabric_external_settings.FABRIC_NAME }}/External_Fabric"
    json_data: "{{ create_fabric_payload | to_json }}"
  when: create_fabric_ext
