---

# ---------------------------------------------------------------- #
# Fabric Settings                                                  #
# ---------------------------------------------------------------- #
fabric_settings:
  vrf_lite:
    BGP_AS: 65001
    GRFIELD_DEBUG_FLAG: "Enable"
    OVERLAY_MODE: "cli"
    VRF_LITE_AUTOCONFIG: "Back2Back&ToExternal"
    DCI_SUBNET_RANGE: "10.31.0.0/16"
    AUTO_SYMMETRIC_VRF_LITE: true
  poap:
    BOOTSTRAP_ENABLE: true
    DHCP_ENABLE: true
    DHCP_IPV6_ENABLE: "DHCPv4"
    DHCP_START: "10.15.0.100"
    DHCP_END: "10.15.0.101"
    MGMT_GW: "10.15.0.1"
    MGMT_PREFIX: "24"
    BOOTSTRAP_MULTISUBNET: "10.15.10.100,10.15.10.101,10.15.10.1,24"

# ---------------------------------------------------------------- #
# Local Fabric Information                                         #
# ---------------------------------------------------------------- #
fabric:
  name: fabric-stage
  asn: 65001
  inventory:
    - seed_ip: 10.15.10.11
      auth_proto: MD5
      user_name: admin
      password: "cisco.123"
      max_hops: 0
      role: spine
      preserve_config: false
    - seed_ip: 10.15.10.12
      user_name: admin
      password: "cisco.123"
      max_hops: 0
      role: leaf
      preserve_config: false
    - seed_ip: 10.15.10.13
      user_name: admin
      password: "cisco.123"
      max_hops: 0
      role: leaf
      preserve_config: false
  spine:
    - ip: 10.15.10.11
  leaf:
    - ip: 10.15.10.12
    - ip: 10.15.10.13

# ---------------------------------------------------------------- #
# POAP Fabric Information                                          #
# ---------------------------------------------------------------- #
fabric_poap:
    name: fabric-stage
    asn: 65001
    enable_poap: true
    inventory:
      - seed_ip: 10.15.10.14
        user_name: admin
        password: "cisco.123"
        role: border
        poap:
          - serial_number: "9IZOB1DARSA"
            model: 'N9K-C9300v'
            version: '9.3(8)'
            hostname: 'staging-leaf3'
            config_data:
            modulesModel: [N9K-X9364v, N9K-vSUP]
            gateway: 10.15.10.1/24
    leaf:
      - ip: 10.15.10.14

# ---------------------------------------------------------------- #
# External Fabric Information                                      #
# ---------------------------------------------------------------- #
fabric_external:
  name: external-fabric-stage
  asn: 9999
  inventory:
    - seed_ip: 10.15.10.15
      auth_proto: MD5
      user_name: admin
      password: "cisco.123"
      max_hops: 0
      preserve_config: true
      role: "edge_router"
  edge_router:
    - ip: 10.15.10.15

