---
vrf_attach_group:
  all_leaf:
    - ip_address: 10.15.10.12
    - ip_address: 10.15.10.13

vrf_lite_attach_group:
  all_leaf:
    - ip_address: 10.15.10.14
      vrf_lite:
        - peer_vrf: AnsibleVRF # optional
          interface: Ethernet1/1 # mandatory
          ipv4_addr: 10.31.0.1/30 # optional
          neighbor_ipv4: 10.31.0.2 # optional
          dot1q: 2 # dot1q can be got from dcnm/optional

attach_group:
  esxi:
    - ip_address: 10.15.10.12
      ports:
        - Port-channel10
    - ip_address: 10.15.10.13
      ports:
        - Port-channel10
