---
# This is the top level build playbook that runs the various
# Ansible roles that will be used to build out the fabric

- name: Build VXLAN EVPN Fabric on NDFC
  hosts: ndfc
  gather_facts: false

  roles:
    - create_fabric
    - add_inventory # Add This Line Under The create_fabric role from the previous section
    - setup_vpc # Add This Line Under The add_inventory role from the previous section
    - manage_interfaces # Add This Line Under The setup_vpc role from the previous section
    - manage_overlay # Add This Line Under The manage_interfaces role from the previous section
    - deploy # Add This Line Under The manage_overlay role from the previous section
