---

- name: Verify Fabric on NDFC
  hosts: ndfc
  gather_facts: false

  tasks:
    - name: verify | check if all VRFs are deployed
      block:
        - name: verify | query all VRFs from {{ fabric_settings.FABRIC_NAME }}
          cisco.dcnm.dcnm_rest:
            path: "/appcenter/cisco/ndfc/api/v1/lan-fabric/rest/top-down/fabrics/{{ fabric_settings.FABRIC_NAME }}/vrfs"
            method: GET
          register: result
        - name: verify | check if status is DEPLOYED
          assert:
            that:
              - item.vrfStatus != "OUT-OF-SYNC"
            quiet: true
          loop: "{{ result.response.DATA }}"

    - name: verify | check if all Networks are deployed
      block:
        - name: verify | query all Networks from {{ fabric_settings.FABRIC_NAME }}
          cisco.dcnm.dcnm_rest:
            path: "/appcenter/cisco/ndfc/api/v1/lan-fabric/rest/top-down/fabrics/{{ fabric_settings.FABRIC_NAME }}/networks"
            method: GET
          register: result
        - name: verify | check if status is DEPLOYED
          assert:
            that:
              - item.networkStatus != "OUT-OF-SYNC"
            quiet: true
          loop: "{{ result.response.DATA }}"
