---
- name: Create and Apply BGP Network Policy To External Router
  cisco.dcnm.dcnm_policy:
    fabric: "{{ fabric_external.name }}"
    state: merged
    config:
      - switch:
        - ip: "{{ fabric_external.edge_router[0].ip }}"
          policies:
            - name: bgp_vrf_network
              create_additional_policy: false
              priority: 500
              policy_vars:
                BGP_AS: 9999
                VRF_NAME: AnsibleVRF
                IP_PREFIX: "172.16.1.1/32"
