---
# tasks file for roles/add_overlay

- ansible.builtin.debug:
    msg:
      - "----------------------------------------------------------------"
      - "+             Calling Role - [add_overlay]                     +"
      - "----------------------------------------------------------------"
  tags:
    - ao_vrfs
    - ao_vrf_lite
    - ao_resync
    - ao_networks
    - ao_policies
    - ao_all

- name: Include Tasks To Add Overlay VRFs
  ansible.builtin.import_tasks: add_vrfs.yml
  tags:
    - ao_vrfs
    - ao_all

- name: Include Tasks To Re-Sync Local and External Fabric Before Adding VRF Lite
  ansible.builtin.import_tasks: resync_fabric.yml
  tags:
    - ao_vrf_lite
    - ao_resync
    - ao_all

- name: Include Tasks To Add Overlay VRFs To VRF Lite Fabric Extensions
  ansible.builtin.import_tasks: add_vrf_lite_vrfs.yml
  tags:
    - ao_vrf_lite
    - ao_all

- name: Include Tasks To Add Overlay Networks
  ansible.builtin.import_tasks: add_networks.yml
  tags:
    - ao_networks
    - ao_all

- name: Include Tasks To Manage Policies
  ansible.builtin.import_tasks: add_policies.yml
  tags:
    - ao_policies
    - ao_all

