---
# tasks file for roles/add_inventory

- ansible.builtin.debug:
    msg:
      - "----------------------------------------------------------------"
      - "+             Calling Role - [add_inventory]                   +"
      - "----------------------------------------------------------------"
  tags:
    - ai_local
    - ai_external
    - ai_query_poap
    - ai_poap
    - ai_all

- name: Include Tasks to Add Devices to Local Fabric
  ansible.builtin.import_tasks: add_devices_local.yml
  tags:
    - ai_local
    - ai_all

- name: Include Tasks To Query For POAP Enabled Switches
  ansible.builtin.import_tasks: query_poap.yml
  when: fabric_poap.enable_poap
  tags:
    - ai_query_poap
    - ai_all

- name: Include Tasks to Add Devices to External Fabric
  ansible.builtin.import_tasks: add_fabric_external.yml
  tags:
    - ai_external
    - ai_all
