---
- name: Query Until POAP Switch Becomes Available
  cisco.dcnm.dcnm_rest:
    method: GET
    path: "/appcenter/cisco/ndfc/api/v1/lan-fabric/rest/control/fabrics/{{ fabric_poap.name }}/inventory/poap"
  register: result
  until: result.response.DATA | length > 0
  retries: 10
  delay: 1
  ignore_errors: true

- ansible.builtin.debug:
    msg: "Serial Number - {{ result.response.DATA[0].serialNumber }}"
  when: result.response.DATA | length > 0

- ansible.builtin.set_fact:
    leaf3_serial_number: "{{ result.response.DATA[0].serialNumber }}"
  when: result.response.DATA | length > 0

- name: Add switches to {{ fabric.name }} Using POAP
  cisco.dcnm.dcnm_inventory:
    fabric: "{{ fabric.name }}"
    state: merged
    config:
      - seed_ip: 10.15.10.14
        user_name: admin
        password: "cisco.123"
        role: border
        poap:
          - serial_number: "{{ leaf3_serial_number }}"
            model: 'N9K-C9300v'
            version: '9.3(8)'
            hostname: 'staging-leaf3'
            config_data:
              modulesModel: [N9K-X9364v, N9K-vSUP]
              gateway: 10.15.10.1/24
  when: result.response.DATA | length > 0
