---
# tasks file for roles/setup_vpc

- ansible.builtin.debug:
    msg:
      - "----------------------------------------------------------------"
      - "+             Calling Role - [setup_vpc]                       +"
      - "----------------------------------------------------------------"
  tags: vpc_all

- name: Query Fabric {{ fabric.name }} Leaf1 and Leaf2 for VPC Configuration
  cisco.dcnm.dcnm_inventory:
    fabric: "{{ fabric.name }}"
    state: query
    config:
      - seed_ip: "{{ fabric.leaf[0].ip }}"
      - seed_ip: "{{ fabric.leaf[1].ip }}"
  register: query_result
  tags: vpc_all

# Use flag variable 'setup_vpc' to track if you need to setup vpc.
# If it's already setup you can skip it
- ansible.builtin.set_fact:
    setup_vpc: True
  tags: vpc_all

- ansible.builtin.set_fact:
    setup_vpc: False
  when: item.isVpcConfigured == true
  loop: "{{ query_result.response }}"
  loop_control:
    label: "{{ item.isVpcConfigured }}"
  tags: vpc_all

- debug: msg="Setup VPC IS - {{ setup_vpc }}"
  tags: vpc_all

- name: Setup VPC Peer If Not Already Setup
  block:
    - name: Include Tasks To Create VPC Peer Between Leaf1 and Leaf2
      ansible.builtin.import_tasks: setup_vpc_peer.yml
  when: setup_vpc
  tags: vpc_all

- name: Query Fabric {{ fabric.name }} Leaf Devices Until vPC Pair Is Configured
  cisco.dcnm.dcnm_inventory:
    fabric: "{{ fabric.name }}"
    state: query
    config:
      - seed_ip: "{{ fabric.leaf[0].ip }}"
      - seed_ip: "{{ fabric.leaf[1].ip }}"
  register: query_result
  until:
    - query_result.response[0].isVpcConfigured
    - query_result.response[1].isVpcConfigured
  retries: 120
  delay: 5
  tags: vpc_all
