---

vrf_lite_attach_group:
  all_leaf:
    - ip_address: 10.15.10.21
      vrf_lite:
        - peer_vrf: AnsibleVRF # optional
          interface: Ethernet1/1 # mandatory
          ipv4_addr: 10.31.0.1/30 # optional
          neighbor_ipv4: 10.31.0.2 # optional
          dot1q: 2 # dot1q can be got from dcnm/optional

